apiVersion: apps/v1
kind: Deployment
metadata:
  name: __APP_NAME__-dc
spec:
  selector:
    matchLabels:
      app: __APP_NAME__-ctr
  replicas: 1
  template:
    metadata:
      labels:
        app: __APP_NAME__
        updateTimestamp: "__TIMESTAMP__"
    spec:
      containers:
      - name: __APP_NAME__-ctr
        image: >-
          __IMAGE__
        env:
          - name: DEPLOY_TIMESTAMP
            value: "__TIMESTAMP__"
        volumeMounts:
        - name: tls-secrets
          readOnly: true
          mountPath: "/var/www/app/tls"
        ports:
        - containerPort: 8080
          name: http
        imagePullPolicy: Always
      volumes:
      - name: tls-secrets
        secret:
          secretName: api-tls-secret